name: Test

on:
  push:
    paths-ignore:
      - .pre-commit-config.yaml
      - '**/*.md'
  pull_request:
    paths-ignore:
      - .pre-commit-config.yaml
      - '**/*.md'
  schedule:
    - cron: '0 0 1 * *' # monthly
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15-intel, macos-14, windows-2025]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install build dependencies (Linux)
        if: runner.os == 'Linux'
        uses: tueda/cache-apt-pkgs-action@v1
        with:
          packages: autoconf-archive
          version: ${{ matrix.os }}-1

      - name: Install build dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install autoconf-archive automake libtool

      - name: Install build dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install pkgconfiglite

      - name: Cache vcpkg binary cache
        uses: actions/cache@v6
        with:
          path: ${{ runner.os == 'Windows' && '~/AppData/Local/vcpkg/archives' || '~/.cache/vcpkg/archives' }}
          key: vcpkg-${{ matrix.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: vcpkg-${{ matrix.os }}-

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg${{ runner.os == 'Windows' && '.bat' || '.sh' }}

      - name: Install dependencies with vcpkg
        run: ./vcpkg/vcpkg install

      - name: Configure the build with CMake
        run: cmake --preset debug

      - name: Build the project
        run: cmake --build build/debug --parallel

      - name: Run tests
        run: cmake --build build/debug --target check --parallel

  clang-tidy:
    name: Clang-Tidy on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Add LLVM APT repository
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key \
            | sudo gpg --dearmor -o /etc/apt/keyrings/apt.llvm.org.gpg
          echo 'deb [signed-by=/etc/apt/keyrings/apt.llvm.org.gpg] http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main' \
            | sudo tee /etc/apt/sources.list.d/llvm-toolchain-noble-22.list
          sudo apt-get update

      - name: Install build dependencies
        uses: tueda/cache-apt-pkgs-action@v1
        with:
          packages: autoconf-archive clang-tidy-22
          version: ${{ matrix.os }}-1

      - name: Cache vcpkg binary cache
        uses: actions/cache@v6
        with:
          path: ~/.cache/vcpkg/archives
          key: vcpkg-${{ matrix.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: vcpkg-${{ matrix.os }}-

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies with vcpkg
        run: ./vcpkg/vcpkg install

      - name: Configure the build with CMake
        run: cmake --preset clang-tidy -DCLANG_TIDY_BIN="$(command -v clang-tidy-22)"

      - name: Build with clang-tidy
        run: cmake --build build/clang-tidy --parallel

  smoke-test-kira:
    name: Smoke test with Kira ${{ matrix.kira-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # NOTE: Kira crashes in this test on the macos-14, macos-15 and macos-26 images.
        # See: https://gitlab.com/kira-pyred/kira/-/work_items/46
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15-intel]
        kira-version: [2.3, 3.1]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install build dependencies (Linux)
        if: runner.os == 'Linux'
        uses: tueda/cache-apt-pkgs-action@v1
        with:
          packages: autoconf-archive libginac-dev libyaml-cpp-dev meson
          version: ${{ matrix.os }}-1

      - name: Install build dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install autoconf-archive automake ginac libtool meson yaml-cpp

      - name: Cache vcpkg binary cache
        uses: actions/cache@v6
        with:
          path: ~/.cache/vcpkg/archives
          key: vcpkg-${{ matrix.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: vcpkg-${{ matrix.os }}-

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies with vcpkg
        run: ./vcpkg/vcpkg install

      - name: Configure the build with CMake
        run: cmake --preset release

      - name: Build the project
        run: cmake --build build/release --parallel

      - name: Build Kira
        run: |
          git clone https://gitlab.com/kira-pyred/kira.git -b '${{ matrix.kira-version }}'
          git -C kira fetch https://gitlab.com/tueda/kira.git 70289ebd5b8e3ed642d430f527b475bc567a462f
          GIT_COMMITTER_NAME='github-actions[bot]' \
            GIT_COMMITTER_EMAIL='41898282+github-actions[bot]@users.noreply.github.com' \
            git -C kira cherry-pick FETCH_HEAD
          meson setup -Db_ndebug=true -Dfirefly=false kira/build kira
          meson compile -C kira/build

      - name: Test
        run: |
          FERMATPATH='${{ github.workspace }}/build/release/src/pierre' \
            meson test -C kira/build --timeout-multiplier 2 --print-errorlogs

      - name: Print test log
        run: cat kira/build/meson-logs/testlog.txt
